name: coptical
description: "Application Calendrier Copte"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.2
  intl: ^0.19.0
  # Services est inclus par défaut dans Flutter,
  # mais assure-toi d'utiliser les dernières versions des plugins.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

# Configuration des icônes (Corrigée)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#161616"
    theme_color: "#D4AF37"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256

flutter:
  uses-material-design: true

  # Déclaration du dossier assets
  assets:
    - assets/